### ISSUE TITLE
HTML5 checking deprecated

### ISSUE THREAD

**Issue by Xinchro** [nikestep/grunt-html-angular-validate#22]
I'm receiving a new error saying that the HTML5 checking is deprecated now. 

##### For normal HTML: 
> [Lundefined:Cundefined] This interface to HTML5 document checking is deprecated.

##### For templates:
> [LNaN:Cundefined] This interface to HTML5 document checking is deprecated.

**Comment by nikestep** [comment]
Looks like W3C has split out the HTML5 validator. I'll look at how to use the new service.

**Comment by raphinesse** [comment]
@nikestep `w3cjs` moved to the new endpoint in version 0.3.0 ([see their issue on it](https://github.com/thomasdavis/w3cjs/issues/17)). However, just switching to the new w3cjs doesn't simply work since the returned data's format seems to have changed. Warnings are no longer filtered for example. Just wanted to let you know.

**Comment by nikestep** [comment]
@raphinesse - Thank you for the contribution, but I was able to incorporate the w3cjs changes, I do believe. I will be adding a note to the readme regarding the upgrade (unfortunately, they slightly changed their messaging).

I am finishing up a release of version 0.5.0 that should get it all back up and running
